compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: NO
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: trainer.train
mixed_precision: 'fp16'
num_machines: 1
num_processes: 1
use_cpu: false